TMP EQU 30H   ; temporary storage
ORG 0000H
CLR P3.3
CLR P3.4

START:	CLR A
LOOP1:	CALL DISP
	JB P2.0, LOOP1
LOOP2:	CALL DISP
	JNB P2.0, LOOP2
	INC A
	DA A
	CALL DISP
	CJNE A, #0F00H, LOOP1
	SJMP START
DISP:	PUSH ACC
	MOV TMP, A
	CALL DECODE
	MOV P1, #0FFH 	; clear display
	CLR P3.3
	CLR P3.4
	MOV P1, A
	MOV A, TMP
	SWAP A
	CALL DECODE
	MOV P1, #0FFH  ; clear display
	SETB P3.3
	CLR P3.4
	MOV P1, A
	POP ACC
	RET
DECODE:	ANL A, #0FH
	MOV DPTR, #LEDCODES
	MOVC A, @A+DPTR
	RET

LEDCODES: DB C0H, F9H, A4H, B0H, 99H, 92H, 82H, F8H, 80H, 90H
END
